Update server cores
GravitLauncher/LauncherWiki pull request #16
Opened 2022-04-09 10:11 UTC by dimadencep

2022-04-09 10:22 UTC, gravit0 requested changes

2022-04-09 10:22 UTC, gravit0 commented on docs/servers/README.md
> +::: tip Информация: <!--Don't add Mohist!-->
Удалите комментарий или впишите туда причину почему Mohist не стоит добавлять

2022-04-09 10:22 UTC, gravit0 commented on docs/servers/README.md
> +  <CodeGroupItem title="1.10.2" active>
Эта версия промежуточная и её нет на зеркале. Нет никакого смысла добавлять ядра на ней

2022-04-09 10:22 UTC, gravit0 commented on docs/servers/README.md
> +  <CodeGroupItem title="1.14.4" active>
Аналогично - это промежуточная версия

2022-04-09 10:22 UTC, gravit0 commented on docs/servers/README.md
> +- [ArcLight](https://github.com/IzzelAliz/Arclight)
Версия 1.15.2 помечена устаревшей в GitHub Arclight

2022-04-09 10:22 UTC, gravit0 commented on docs/servers/README.md
> +Не используйте ядро [Mohist](https://mohistmc.com) - это самое отвратительное по производительности ядро, по сравнению с вышеприведенными ядрами!
Приведите тесты производительности для сравнения Mohist с другими ядрами, а так же ссылки на critical баги

2022-04-09 12:48 UTC, dima-dencep commented on docs/servers/README.md
> +Не используйте ядро [Mohist](https://mohistmc.com) - это самое отвратительное по производительности ядро, по сравнению с вышеприведенными ядрами!
А зачем приводить баги, если их можно увидеть [тут](https://github.com/MohistMC/Mohist/issues)
Скорее всего, критичные те, которые закреплены

2022-04-09 12:51 UTC, dimadencep commented on docs/servers/README.md
> +Не используйте ядро [Mohist](https://mohistmc.com) - это самое отвратительное по производительности ядро, по сравнению с вышеприведенными ядрами!
Тесты еще давным давно проводил day-d если вам этого не достаточно, могу сделать тест с loliserver на 1.16.5

2022-04-09 12:53 UTC, gravit0 commented on docs/servers/README.md
> +Не используйте ядро [Mohist](https://mohistmc.com) - это самое отвратительное по производительности ядро, по сравнению с вышеприведенными ядрами!
Все тесты нужно оформить и добавить на вики. Или ссылку на них в открытом доступе. Ссылка на бег-трекер так же должна быть

2022-04-11 22:04 UTC, JoCat commented on docs/servers/README.md
> +Не используйте ядро [Mohist](https://mohistmc.com) - это самое отвратительное по производительности ядро, по сравнению с вышеприведенными ядрами!
[Список ишью с фильтром по багам](https://github.com/MohistMC/Mohist/issues?q=is%3Aopen+is%3Aissue+label%3ABug)

2022-05-08 12:05 UTC, merged